<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            // Admin
            [
                'first_name'=> 'Admin',
                'last_name' => 'Admin',
                'username'  => 'admin',
                'email'     => 'admin@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01075563321',
                'role'      => User::ROLE_ADMIN,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            // Doctor
            [
                'first_name'=> 'Mohamed',
                'last_name' => 'Okasha',
                'username'  => 'MohamedOkasha2',
                'email'     => 'mohamedokasha@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01012345678',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Ahmed',
                'last_name' => 'Elharby',
                'username'  => 'AhmedElharby3',
                'email'     => 'ahmedElharby@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01023456789',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Wael',
                'last_name' => 'Abdelqader',
                'username'  => 'WaelAbdelqader4',
                'email'     => 'waelAbdelqader@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01034567890',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Nasma',
                'last_name' => 'Ibrahim',
                'username'  => 'NasmaIbrahim5',
                'email'     => 'nasmaIbrahim@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01045678901',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Heba',
                'last_name' => 'Alhadidi',
                'username'  => 'HebaAlhadidi6',
                'email'     => 'hebaAlhadidi@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01067890123',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Ahmed',
                'last_name' => 'Rabie',
                'username'  => 'AhmedRabie7',
                'email'     => 'ahmedRabie@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01078901234',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Tamer',
                'last_name' => 'Emara',
                'username'  => 'TamerEmara8',
                'email'     => 'TamerEmara@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01089012345',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Abeer',
                'last_name' => 'Saber',
                'username'  => 'AbeerSaber9',
                'email'     => 'abeerSaber@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01090123456',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Amira',
                'last_name' => 'AlZaini',
                'username'  => 'AmiraAlzaini10',
                'email'     => 'amiraAlzaini@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01001234567',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Mohamed',
                'last_name' => 'Salah',
                'username'  => 'MohamedSalah11',
                'email'     => 'mohamedSalah@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01011223344',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            // User
            [
                'first_name'=> 'User',
                'last_name' => 'User',
                'username'  => 'user',
                'email'     => 'user@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> '2024501',
                'phone'     => '01096653381',
                'role'      => User::ROLE_USER,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'User2',
                'last_name' => 'User2',
                'username'  => 'user2',
                'email'     => 'user2@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> '2024502',
                'phone'     => '01096653382',
                'role'      => User::ROLE_USER,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'User3',
                'last_name' => 'User3',
                'username'  => 'user3',
                'email'     => 'user3@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> '2024503',
                'phone'     => '01096653383',
                'role'      => User::ROLE_USER,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'User4',
                'last_name' => 'User4',
                'username'  => 'user4',
                'email'     => 'user4@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> '2024504',
                'phone'     => '01096653384',
                'role'      => User::ROLE_USER,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'User5',
                'last_name' => 'User5',
                'username'  => 'user5',
                'email'     => 'user5@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> '2024505',
                'phone'     => '01096653385',
                'role'      => User::ROLE_USER,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'User6',
                'last_name' => 'User6',
                'username'  => 'user6',
                'email'     => 'user6@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> '2024506',
                'phone'     => '01096653386',
                'role'      => User::ROLE_USER,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'User7',
                'last_name' => 'User7',
                'username'  => 'user7',
                'email'     => 'user7@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> '2024507',
                'phone'     => '01096653387',
                'role'      => User::ROLE_USER,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'User8',
                'last_name' => 'User8',
                'username'  => 'user8',
                'email'     => 'user8@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> '2024508',
                'phone'     => '01096653388',
                'role'      => User::ROLE_USER,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
        ]);
    }
}
