<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            // Admin
            [
                'first_name'=> 'Admin',
                'last_name' => 'Admin',
                'username'  => 'admin',
                'email'     => 'admin@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01075563321',
                'role'      => User::ROLE_ADMIN,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            // Doctor
            [
                'first_name'=> 'Mohamed',
                'last_name' => 'Okasha',
                'username'  => 'MohamedOkasha2',
                'email'     => 'mohamedokasha@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01012345678',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Ahmed',
                'last_name' => 'Elharby',
                'username'  => 'AhmedElharby3',
                'email'     => 'ahmedElharby@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01023456789',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Wael',
                'last_name' => 'Abdelqader',
                'username'  => 'WaelAbdelqader4',
                'email'     => 'waelAbdelqader@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01034567890',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Nasma',
                'last_name' => 'Ibrahim',
                'username'  => 'NasmaIbrahim5',
                'email'     => 'nasmaIbrahim@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01045678901',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Heba',
                'last_name' => 'Alhadidi',
                'username'  => 'HebaAlhadidi6',
                'email'     => 'hebaAlhadidi@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01067890123',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Ahmed',
                'last_name' => 'Rabie',
                'username'  => 'AhmedRabie7',
                'email'     => 'ahmedRabie@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01078901234',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Tamer',
                'last_name' => 'Emara',
                'username'  => 'TamerEmara8',
                'email'     => 'TamerEmara@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01089012345',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Abeer',
                'last_name' => 'Saber',
                'username'  => 'AbeerSaber9',
                'email'     => 'abeerSaber@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01090123456',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Amira',
                'last_name' => 'AlZaini',
                'username'  => 'AmiraAlzaini10',
                'email'     => 'amiraAlzaini@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01001234567',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Mohamed',
                'last_name' => 'Salah',
                'username'  => 'MohamedSalah11',
                'email'     => 'mohamedSalah@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> null,
                'phone'     => '01011223344',
                'role'      => User::ROLE_SUPERVISOR,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            // User
            [
                'first_name'=> 'Maged',
                'last_name' => 'Salah',
                'username'  => 'MagedSalah12',
                'email'     => 'magedSalah@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> '202412',
                'phone'     => '01096653381',
                'role'      => User::ROLE_USER,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Mahmoud',
                'last_name' => 'Salah',
                'username'  => 'MahmoudSalah13',
                'email'     => 'mahmoudSalah@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> '202413',
                'phone'     => '01096653382',
                'role'      => User::ROLE_USER,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Omar',
                'last_name' => 'Abdo',
                'username'  => 'OmarAbdo14',
                'email'     => 'omarAbdo@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> '202414',
                'phone'     => '01096653383',
                'role'      => User::ROLE_USER,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Ahmed',
                'last_name' => 'Amin',
                'username'  => 'AhmedAmin15',
                'email'     => 'ahmedAmin@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> '202415',
                'phone'     => '01096653384',
                'role'      => User::ROLE_USER,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Khaled',
                'last_name' => 'Ahmed',
                'username'  => 'KhaledAhmed16',
                'email'     => 'khaledAhmed@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> '202416',
                'phone'     => '01096653385',
                'role'      => User::ROLE_USER,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Maged',
                'last_name' => 'Maher',
                'username'  => 'MagedMaher17',
                'email'     => 'magedMaher@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> '202417',
                'phone'     => '01096653386',
                'role'      => User::ROLE_USER,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
            [
                'first_name'=> 'Omar',
                'last_name' => 'Ali',
                'username'  => 'OmarAli18',
                'email'     => 'omarAli@gmail.com',
                'is_change_password'=> 1,
                'password'  => Hash::make('12345678'),
                'student_id'=> '202411',
                'phone'     => '01096653387',
                'role'      => User::ROLE_USER,
                'created_at'=> now(),
                'updated_at'=> now(),
            ],
        ]);
    }
}
